### ISSUE TITLE
appears invoked on a non-main thread

### ISSUE THREAD

**Issue by redbunnys** [aprox2/SuperheroPlugin#2]
I got an error when using the Command lvl command. I am a newbie and I don’t know how to solve it. The command cannot be called.
Superhero Version：0.0.13
CounterStrikeSharp Version: v203

![image](https://github.com/aprox2/SuperheroPlugin/assets/58156215/0e7026bf-59c1-4216-9529-bd92d8a68cde)

**Comment by aprox2** [comment]
Yeah Ill try to look into this, this weekend. Some of the code is old and probably Im trying to access player not inside the main thread, which was possible few versions ago.

**Comment by redbunnys** [comment]
ok, looking forward to it very much
